import = [
    "~/.config/alacritty/themes/aura.toml"
]

[font]
size = 35

[font.normal]
family = "SpaceMono Nerd Font"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[window]
decorations = "none"
dynamic_padding = false
blur = true
opacity = 0.85
startup_mode = "Fullscreen"

[window.padding]
x = 7
y = 0
